name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: clone
      uses: actions/checkout@v2
    - name: Install extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: pecl
        extensions: intl
    - name: Composer
      run: |
          composer install --no-ansi --no-interaction --no-suggest --prefer-dist
    - name: Run Unit Tests
      run: |
        cd $GITHUB_WORKSPACE
        ./vendor/bin/phpunit
  deploy:
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' || github.ref == 'refs/heads/master' }}
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude '.env'"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }} 
          TARGET: ${{ secrets.REMOTE_TARGET }}